# Generated by Django 3.2.2 on 2023-04-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='org_title',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='wage',
            new_name='next_paycheck_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='next_paycheck_date',
        ),
    ]
