# Generated by Django 3.2.2 on 2023-04-15 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_auto_20230415_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='organization',
        ),
    ]
