# Generated by Django 3.2.2 on 2023-04-15 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_remove_loan_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.organization'),
        ),
    ]
