# Generated by Django 3.2.2 on 2023-04-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_loan_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='borrowing_amount',
            field=models.FloatField(blank=True, default=100),
        ),
    ]
